### ISSUE TITLE
Not much of a issue, but still, had nowhere to ask it

### ISSUE THREAD

**Issue by Nextshot** [Zetrith/Multiplayer#103]
I have a friend that wants to play with me, but the mod seems to not work on non-steam versions, for me it works fine, just subscribed and done, he dropped the mod on the mods folder and it didnt work

**Comment by Nextshot** [comment]
He says that the multiplayer buttons doesnt even shows up.

**Comment by SilentBob92PL** [comment]
Try this https://github.com/Parexy/Multiplayer

**Comment by Nextshot** [comment]
Still, the button doesnt shows up to him, his looks like default rimworld and mine looks like this: (which is what I was expecting to it look like into his too)
![image](https://user-images.githubusercontent.com/16524374/66692958-0674e480-ec7a-11e9-95ed-12e089a32098.png)

**Comment by sTiKyt** [comment]
Maybe he not enabled it in "Mods"?..
