### ISSUE TITLE
Forced gear and pawn restrictions' names synchronization fails

### ISSUE THREAD

**Issue by drspangle** [Zetrith/Multiplayer#12]
As the name implies, but here are some extra details.

- Forced equipping gear gets 'stuck' and can't be undone by the client or the host, attempting to do so doesn't work and causes desync whether the host or the client tells the pawn to unequip the gear

- The names of gear restriction, food restriction, and drug regimens fails to sync; when the client creates it, the host sees it with a generated name; when the host creates it, the name usually syncs, but the client can't change the name

**Comment by Zetrith** [comment]
Fixed in 0.4

**Comment by Zetrith** [comment]
It works fine in vanilla. Could've been some mod interfering. Should be fixed in 0.4.3.
