### ISSUE TITLE
DNS resolution doesn't work for direct connect

### ISSUE THREAD

**Issue by drspangle** [Zetrith/Multiplayer#13]
This is a feature request, but may be a bug if it's supposed to work this way...

When using the "direct connect" menu tab when joining a multiplayer game, you must enter an IP address. When names are entered, DNS resolution doesn't happen, and the client fails to join.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I am not a programmer, but the code seems pretty legible. I don't think it attempts DNS resolution.
