### ISSUE TITLE
Leaving an enemy outpost breaks travel

### ISSUE THREAD

**Issue by michaelbellgh** [Zetrith/Multiplayer#14]
In a multiplayer game of 2, when leaving an enemy outpost after a successful quest, the caravan no longer moves towards its destination. 
Also, when selecting a route and then pressing the accept button, a selection of items disappear from the caravan loading screen, and the screen does not close.

I can re enter the enemy outpost (and the icon says 2.X days till leaving) and exit again, but same result

No issues in version 0.3, and this is from a 0.3 save. Did the /autosave command twice before upgrading the mod.

**Comment by Zetrith** [comment]
Fixed in 0.4.2
