### ISSUE TITLE
Desync on Random Events

### ISSUE THREAD

**Issue by sg1apropgis** [Zetrith/Multiplayer#19]
Me and my Friend just tried out 0.4.3 He was Hosting and and im Joining and at some Random Events i get the Desync Message.. Not sure if its only Related to the Events.

Including a few of myDesync Files

Rimworld 1.0
Win 10 x64
German Lang
Steam, The Arbiter, dev-mode ,  enabled

[Desync-04.zip](https://github.com/Zetrith/Multiplayer/files/2776671/Desync-04.zip)
[Desync-10.zip](https://github.com/Zetrith/Multiplayer/files/2776672/Desync-10.zip)
[Desync-06.zip](https://github.com/Zetrith/Multiplayer/files/2776673/Desync-06.zip)

**Comment by Zetrith** [comment]
Should be fixed in 0.4.4
