### ISSUE TITLE
Hamachi support

### ISSUE THREAD

**Issue by CajetanP** [Zetrith/Multiplayer#23]
Is it somehow possible to play using this mod through Hamachi (or any other emulated lan network)? It seems to me that it always opens a server on a local "physical" network and it's not possible to change it to a virtual one, like Hamachi. Do you think it would be feasible?

**Comment by drspangle** [comment]
@CajetanP This mod already supports virtual networks and VPNs - you need to make sure that your OS has the routing tables/hostfile configured such that it knows which interface to use to access the remote IP address. 

This is not something that is explicitly supported by the mod itself, it's always going to be configured at the OS level, under your networking configuration. If you're talking about discovery of local "LAN" games by doing discovery through the VPN interface via broadcast traffic, that might be a different story. I think that shouldn't matter. If you know the IP address of the remote host, your machine should route to it through the correct adapter. This is closely related to #13.

**Comment by Zetrith** [comment]
Yeah, Hamachi and other VPNs do work already. You need to use direct host/connect for that.  
More info: https://github.com/Zetrith/Multiplayer/wiki/Hosting-and-joining
