### ISSUE TITLE
Workshop support or Autoupdater

### ISSUE THREAD

**Issue by MartinX3** [Zetrith/Multiplayer#25]
Will this Mod be placed in the Workshop or get an Autoupdater (Using new Github releases) or at least an notification for every new Version (Checking Github releases)?

Anyway, thank you for your work!

**Comment by Zetrith** [comment]
Workshop release will be available after the mod gets more stable. The mod supports Mod Manager which has some version checking features.
https://github.com/Zetrith/Multiplayer/wiki/FAQ

**Comment by MartinX3** [comment]
Maybe you want to create a Issue Template containing a checkbox like "I did read the FAQ.." ?
