### ISSUE TITLE
Bypass mod checks

### ISSUE THREAD

**Issue by drspangle** [Zetrith/Multiplayer#28]
I'm trying to run a mod on my client that doesn't touch anything except the UI, but the server and all other clients need to have this installed in order for us to play multiplayer. If the server could allow mod checks to be bypassed with a whitelist (or perhaps set mods as "required"?) then we'd all be happy.

**Comment by Zetrith** [comment]
What's the mod? Multiplayer only checks the most necessary things.

**Comment by drspangle** [comment]
RimHUD. You're saying I ought to be able to connect while using it, even if the server doesn't have it?

**Comment by Zetrith** [comment]
Yes, can you not?

**Comment by drspangle** [comment]
I'm going to run a test now to confirm.

**Comment by drspangle** [comment]
It was the Blueprints mod. Whoops. You can close this.
