### ISSUE TITLE
Cant join

### ISSUE THREAD

**Issue by Botino123** [Zetrith/Multiplayer#29]
I cant join my friend via steam as my name doesn't show up on the list where he is supposed to accept my connection, the same thing happens for me if he tries to join.

**Comment by Zetrith** [comment]
Check out https://github.com/Zetrith/Multiplayer/wiki/Hosting-and-joining
Try using other connections methods (like Hamachi) if it still doesn't work.

**Comment by Botino123** [comment]
Thank you for the quick reply! I finally managed to get it to work, after both me and my friend reinstalled the mod we turned on the setting to auto accept any connections from steam, which did the trick.
