### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by skyne98** [Zetrith/Multiplayer#3]
Hello there,
I believe you are doing a fantastic job, but it would be nice to track the progress somewhere, is it possible?

Also, maybe there should be a place with "low-hanging" tasks we can help with!

**Comment by Zetrith** [comment]
I'll be sure to add such tasks as issues when they appear. For now though, I think most of them require quite an in-depth knowledge of how the mod works.

**Comment by skyne98** [comment]
Btw, check your mod with my friend a couple of days ago and I have to say -- nice job! It runs very, very good and even supports some mods 👍
