### ISSUE TITLE
[Feature] Smart speed selection

### ISSUE THREAD

**Issue by Thanaen** [Zetrith/Multiplayer#35]
Hi,

I thought of an interesting feature: a kind of "intelligent" management of game speed.
Overall, each player could choose the speed at which they want to go, and the game will go at the speed closest to everyone's choices.
For example:
Player 1 chooses speed 3 (max)
Player 2 chooses speed 2
Player 3 chooses speed 2

[example added for more clarity]
Then the game goes to speed 2.

Player 1 chooses speed 2
Player 2 chooses speed 2
Player 3 chooses speed 2
Player 4 chooses speed 1

Then the game goes to speed 1.

I think it would make games with many players more enjoyable, and it would prevent accidents during the fights of some players!

If I can participate in the development of this feature, I would be happy to do so!

Thank you in advance for reading, sorry for the lack of formalism

**Comment by arkaion** [comment]
Hey !

Good idea, but it may be better if the game choose the lowest selected game speed.
For exemple : 
Player 1 : Speed x3
Player 2 : Speed x3
Player 3 : Speed x1

Then the game goes to x1

With your method, if 7 players choose x3 and the eighth want x1, then it will still go x3 (if I understood correctly).

**Comment by Thanaen** [comment]
> 
> 
> Hey !
> 
> Good idea, but it may be better if the game choose the lowest selected game speed.
> For exemple :
> Player 1 : Speed x3
> Player 2 : Speed x3
> Player 3 : Speed x1
> 
> Then the game goes to x1
> 
> With your method, if 7 players choose x3 and the eighth want x1, then it will still go x3 (if I understood correctly).

I might have explained it badly, because we're thinking of the same system!
The lowest set speed will always be the server's speed!

That's the best I could think about to protect players being attacked while allowing easier speed management

**Comment by TupiNUMBooR** [comment]
I was going to suggest "lowest speed" feature too, until i saw this discussion.
Looks like a lot of people want this!

**Comment by Thanaen** [comment]
Sadly I haven't seen much feedback from the devs, and the number of issues is starting to grow! Looks like the devs are busy
