### ISSUE TITLE
Desync on trade

### ISSUE THREAD

**Issue by Rob117** [Zetrith/Multiplayer#37]
Trading, via caravan or bulk trader, causes desync.

**Comment by Rob117** [comment]
Follow up - 
When hosting a game that has experienced this issue and turning off arbiter to assure localhost, the trade menu pops up for a frame, then disappears.

**Comment by Rob117** [comment]
As another addendum, when trying to form a caravan after this occurs, selecting colonists will show that they are enabled with a green checkmark, but the walking speed remains 0, carry load remains 0, and trying to choose route give an error about non-downed colonists (both were fine)

**Comment by Rob117** [comment]
Note - Dev tools enabled with "Select everything" causes the caravan to load all items, but deselecting, enabling/disabling through the UI does nothing.

**Comment by Rob117** [comment]
The reset button also works after Dev: select everything

**Comment by Rob117** [comment]
Last message - Debug log gives an Null Ref for Multiplayer.Client.TradingWindow, logs attached:
https://git.io/fhSOy

**Comment by Rob117** [comment]
Okay, so I REALLY didn't intend to leave all these comments, but probably maybe last comment no promises anymore.

Quitting to OS and restarting fixed everything.

**Comment by Mihokyo** [comment]
Making caravane when you have at least 1 caravane already in activity or have 2 colonies makes the other player than host can't add stuff/people/beast in the new caravane

We was playing in fully vanilla

**Comment by DrGirlfriend** [comment]
I have run into this one also but only once so far - I remember during the caravan trade (while the trade window was open) and a couple of automatic saves invoked, then the dsynce occured. Trying to resync caused the game to hang on both host and client.
[Desync-01.zip](https://github.com/Zetrith/Multiplayer/files/3316989/Desync-01.zip)
