### ISSUE TITLE
Mod - RimHUD - Self heal cause desync

### ISSUE THREAD

**Issue by SoEnguy** [Zetrith/Multiplayer#38]
I know this is mod compatibility related, however it might help fix other issues.
When using RimHUD mod, if you set the self-heal attribute through the rimhud, it causes you to desync. Self heal through the regular button works fine though.

**Comment by Dunkhan** [comment]
As mentioned in #39 there is a warning when a job is generated through interface buttons. I think this is actually an issue with the multiplayer mod as it effects multiple other mods. The fact that the programmer inserted a warning to be logged when this happens suggests that this is not an unknown problem.
