### ISSUE TITLE
Comms Console: Plans for calling other factions?

### ISSUE THREAD

**Issue by jaytaylor** [Zetrith/Multiplayer#42]
Hi Zetrith,

Thank you so much for making multiplayer.  You are INCREDIBLE!!!  It's so amazingly awesome, words can't express how highly I respect and admire what you've pulled off.  Truly impressive.

Gameplay is generally seamless and flawless.  The only aspect my friends and I have encountered so far that we'd like to see change is the ability to call other factions to trade via the Comms Console.

In the right-click menu of the Comms Console, I noticed this message:

> Calling other factions is currently not available in multiplayer.

Since the in-game message says "currently not available", does this mean there are plans or possibilities to have it implemented?  What are the hurdles or challenges for this functionality?  If you have an idea of how to make it work, maybe I could even help (I love programming :).

Thanks again!  Rimworld was great to play before, and your mod brings a new dimension that takes the fun factor totally over the top!

Best Regards,
Jay

**Comment by Totherphoenix** [comment]
Bump! :)

**Comment by WheatTail** [comment]
Hello, dear developer! We with friend (and a lot of people seems to do too) will be really glad to see that feature working, cuz sometimes you really need to request a trade. Also here are some mods like "More Factions Interactions" and "Raids For Me" seems to require working comm console :( Please, hear our whining D:

**Comment by CreeperMaxCZ** [comment]
Hello, I would also be very happy if you fix it.
