### ISSUE TITLE
Hosting a saved multiplayer replay but most of the game is blacked out

### ISSUE THREAD

**Issue by DreamNow33** [Zetrith/Multiplayer#46]
Loaded a saved multiplayer replay and during simulating the server, and when it finishes the screen is blacked out.

Some items like fires, corpses, and animals will show. However, colonists, the ground etc. won't show.

I am using mods, and my gf and I have played successfully before, and have hosted again after we desynced before so we have managed hosting a saved replay.

**Comment by Zetrith** [comment]
Could you send me your output log and the list of mods you are using?
See https://github.com/Zetrith/Multiplayer/wiki/FAQ for file locations

**Comment by DreamNow33** [comment]
[output_log.txt](https://github.com/Zetrith/Multiplayer/files/2851441/output_log.txt)

These are the mods. Could a steam update of a mod have caused this issue? It was a couple days been sessions so likely one could have been updated.

[FSF] Efficient Utilities
[FSF] Rain Washes Away Filth
[KV] RimFridge - 1.0
[KV] Trading Spot - 1.0
[SYR] Doormats
Damage Indicators
EdB Prepare Carefully
HugsLib
Interaction Bubbles
Let's Trade! [1.0]
Medieval Times
Mod Manager
Pick Up And Haul
Realistic Rooms
VGP Garden Medicine
VGP Garden Tools
VGP Vegetable Garden
VGP_CoffeeTeaDrugs
Weapon Tech
While You're Up [1.0]
