### ISSUE TITLE
same speed as the host

### ISSUE THREAD

**Issue by Johari12** [Zetrith/Multiplayer#48]
The time is synchronized with the host and vice versa, when I change the speed and the host speed also changes 
Villages far away from each other

Written with https://translate.google.com :)

**Comment by drunlade** [comment]
Game speed has to be universal across all clients - it wouldn't be possible to have people playing at different speeds, no matter which "zone" you are currently looking at.

**Comment by Johari12** [comment]
> Скорость игры должна быть универсальной для всех клиентов - невозможно, чтобы люди играли на разных скоростях, независимо от того, какую «зону» вы сейчас просматриваете.

At that moment, it does not work 
https://youtu.be/ZOaf524Z7P4?t=208

he paused the game with a button at the top of the screen
I do not have such a button
