### ISSUE TITLE
Mod Mismatch

### ISSUE THREAD

**Issue by Triscuit003** [Zetrith/Multiplayer#50]
Tried joining a friend however I got a "mod definition mismatch". However under details the mod list for both host and myself are exactly the same. (its vanilla rimworld without mods) Any idea of how to fix this?

**Comment by Triscuit003** [comment]
Nevermind, found that there were specific scripts in my core folder that were mismatched.

**Comment by WaKeMaTTa** [comment]
We need some better UI to solve this mismatches. @Zetrith can you add at least the version number of each mod

**Comment by WaKeMaTTa** [comment]
@Zetrith What about creating a md5 hash for each mod at the runtime this way you can send this information from the host to the guest and tell him witch mod doesn't match.

**Comment by WaKeMaTTa** [comment]
@Zetrith ping

**Comment by CorbontheCob** [comment]
So how is this fixed?
