### ISSUE TITLE
3 Player...

### ISSUE THREAD

**Issue by WJRev** [Zetrith/Multiplayer#51]
Just to start with. Incredible work, I never thought this would be possible.

Me and two of my friends are playing a game where we each have our own base. And it's working great. However, one of the lads is playing on his laptop now his internet isn't the best but his ticks gradually get worse and worse until we have to pause. He is playing on a laptop that isn't great. Is the ticks building more likely to be internet or hardware based?

**Comment by arkaion** [comment]
I have the same problem playing with two of my friends.
They both have high tier PC and god tier internet connection, where I have meh tier on both.
I am currently upgrading my computer, so I will soon be able to say if it comes from the hardware.
(currently, going into x3 speed lower my fps to around 5-15, and my ticks go from 20-30 to 500+ in less than 30 seconds)

**Comment by AlexLeporiday** [comment]
From my, somewhat limited, understanding if your game is running slower than everyone else's then you will constantly need to sync the game when it detects sync issues. RimWorld follows a 60 ticks a second (Likely originally designed to match with FPS of the game) so if your FPS is dropping below playable levels it's likely that your also going out of sync with the other players. It's very unlikely to be an internet issue unless you have extremely high latency or are dropping a lot of packets that can't be synced in the background.
