### ISSUE TITLE
Constant Resync

### ISSUE THREAD

**Issue by Nitram101** [Zetrith/Multiplayer#53]
Me and my friend are playing the game and I constantly have to re sync this issue has happened whenever we play the game.

**Comment by pronyacat** [comment]
Check your mods.

**Comment by TheBannaKing** [comment]
what mods cause this im also having the same issues with mods on

**Comment by Nitram101** [comment]
send your list of mods and I will take a look

**Comment by Pure-NaCl** [comment]
I am also getting this with me and a friend after the first 2- 3 days in game it starts and just ramps up till we cant take it any more.
Mod List:
![2019-03-10 05_56_24-RimWorld by Ludeon Studios](https://user-images.githubusercontent.com/48391208/54075956-557c2500-42f9-11e9-94c1-98eb6af14c7d.png)
