### ISSUE TITLE
Not really a issue just ?

### ISSUE THREAD

**Issue by Dirtydan111** [Zetrith/Multiplayer#55]
Whats the recommended amount of mods u can have without ur server constantly needed to be resync with non hosting players heres a list of my mods so that maybe one of the mods is making it desync
![20190215142928_1](https://user-images.githubusercontent.com/47675860/52882870-a9e31900-312e-11e9-937e-d1595a48e245.jpg)
![20190215142939_1](https://user-images.githubusercontent.com/47675860/52882871-aa7baf80-312e-11e9-90c6-4f739ded9981.jpg)
![20190215142920_1](https://user-images.githubusercontent.com/47675860/52882872-ab144600-312e-11e9-8f8a-f60519026fbf.jpg)

**Comment by jacobEAdamson** [comment]
The amount of mods is not the issue most likely. Some mods can cause desyncs on multiplayer. I would recommend using the spreadsheet on [this page](https://github.com/Zetrith/Multiplayer/wiki/Mod-support) to see which of your mods are incompatible with multiplayer.
