### ISSUE TITLE
Incompatibility: Custom textures?

### ISSUE THREAD

**Issue by Totherphoenix** [Zetrith/Multiplayer#57]
I have been playing the Adeptus Astartes mod with a friend, and it runs almost seamlessly, except for when Daemons spawn - their purple flames seem to consistently desync our games whenever our walls are hit by the Daemon Fire...

Any reason this could be happening / is there a plan to make mods like this, Rimhammer, etc. (overhauls) compatible?

Thanks a lot for  your work - this mod is incredible.

**Comment by jacobEAdamson** [comment]
There is a plan to support those kinds of mods, but currently you can use [this](https://github.com/Zetrith/Multiplayer/wiki/Mod-support) resource to give you a good idea of exactly which mods are supported right now
