### ISSUE TITLE
better way to tell what mods is miss mach

### ISSUE THREAD

**Issue by jal21** [Zetrith/Multiplayer#60]
me and a friend have been having problems whit connecting to each other and we have tried nerly all the fixes that we have been sent. all i need to know is what is not right so i can fix it

**Comment by jacobEAdamson** [comment]
If the problem is that the game is telling you you have the wrong mods compared to the server, please disable all mods besides multiplayer and hugslib on both the server and the client, and try to connect that way.

**Comment by sirdoombox** [comment]
As long as both of you have the correct mods installed, you can just send the `ModsConfig.xml` file across located in `C:\Users\[Username]\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config`

It's a bit of a dirty hack but it was the quickest way for myself and my friend to just get it working right out of the gate.
