### ISSUE TITLE
Host Game with Direct Connect

### ISSUE THREAD

**Issue by TheSilverNuke** [Zetrith/Multiplayer#61]
Unsure how to do this, it just provides me with the local ip 192.168.0.10 and a port number of which my buddy connects to and it doesn't process.

**Comment by TheSilverNuke** [comment]
Apparently I should be port forwarding? I'm unsure what the correct ports are for this.

**Comment by PhantomGamers** [comment]
You have to forward TCP 21025, keep your local IP in the direct connect box and then give your friend your public ip found here: https://www.google.com/search?q=what+is+my+ip

**Comment by TheSilverNuke** [comment]
Thanks very much!
