### ISSUE TITLE
Allow enabling debug mode at runtime

### ISSUE THREAD

**Issue by werner291** [Zetrith/Multiplayer#64]
Hello!

Currently, debug mode can be enabled at compile time: https://github.com/Zetrith/Multiplayer/blob/85c5341dbdfeef18bea21ab76c432e9e44e4c4c3/Source/Common/Version.cs

The debug tools look very useful, especially this one: https://github.com/Zetrith/Multiplayer/blob/7844d86a859bb18766ca9795ba5b42fd2536c0cb/Source/Client/DebugTools.cs#L31

Especially for things like checking definition mismatches, which right now pretty much just throws a hash mismatch error and calls it a day.

However, the problem is that accessing these requires enabling debug mode, which requires recompiling the mod.

It would be useful if we could somehow enable these tools at runtime, in order to find out which mod is causing the hash mismatch problem.

**Comment by jacobEAdamson** [comment]
We're you able to compile the mod? I've been stuck with finding the right dll for the assembly csharp public file
