### ISSUE TITLE
Multiplayer doesn't show up in mod order list.

### ISSUE THREAD

**Issue by Barry52** [Zetrith/Multiplayer#65]
It's not shown but the button shows up. So I can use the mod but can't play with anyone because the multiplayer mod doesn't show in the mod list.

**Comment by sbacklund2013** [comment]
You cannot have any other mods enabled. Make sure you have unzipped the mod into the proper folder.

**Comment by Barry52** [comment]
Thanks for the help must have been one of the mods I had.
