### ISSUE TITLE
Author does not appear and not compatible with newest version?

### ISSUE THREAD

**Issue by ItsYaBoiSnakon** [Zetrith/Multiplayer#68]
A friend of mine downloaded the latest version of this mod (0.4.4) for Rimworld 1.0.2150 , so did I. For me it worked just fine, but for my friend it said it is not compatible with the current version of Rimworld? We have no idea how to fix this. Are other mods causing this problem? We tried to disable as much mods as possible, but it still didn't work for him.

**Comment by MetalOwnlife** [comment]
I am currently running into the same problem. Got it loaded in fine on a friend's Mac but got an error on my PC. It said the same thing about it being incompatible with the current version, too. Didn't have any other mods running at the time.

**Comment by Reploidsham** [comment]
If you're having issues with it not working, try going to your rimworld install folder, go into mods, and delete /Core/. Once you do this, use Steam to re-verify the files and it should fix the problem.
