### ISSUE TITLE
Desync and not able to re-sync

### ISSUE THREAD

**Issue by qsdoosix** [Zetrith/Multiplayer#69]
Me and my friend have tried this mod, it works fine for first few minutes, but then we get a desync, i have the arbiter running so we tried to re-sync, but it never finish, and in fact as he simulating, the ticks behind is increasing instead of reducing. (It starts to reduce at the beginning, but after some point it goes increasing again)

**Comment by tindolt** [comment]
What mods are you using? did you  check to see if they were compatible? are your mod settings the same for both host and clients? How good are your pcs? what game speed are you running at? How good is your internet connection for everyone? lots of factors here bud

**Comment by KalleE20** [comment]
Hello guys, i have the same issue, whe have not the same settings for our clients and our pcs are realy good, the speed is 2x, our internet connection is good so we do not know what is wrong. Do anybody know whats the problem?

**Comment by qsdoosix** [comment]
> Hello guys, i have the same issue, whe have not the same settings for our clients and our pcs are realy good, the speed is 2x, our internet connection is good so we do not know what is wrong. Do anybody know whats the problem?

Check all your mod settings. Our problem is we both use the increase stack limit mod. But i set to 750 per stack, but my friends set to 375.

**Comment by KalleE20** [comment]
We had check it, now we have the same mods and settings, and only played on 1x somit we dont know now why it happens
