### ISSUE TITLE
Add instructions for building to README

### ISSUE THREAD

**Issue by jacobEAdamson** [Zetrith/Multiplayer#70]
Right now, there's a complicated step for creating a publicized version of the Rimworld assembly involved in building this mod. I've taken the liberty of converting the original gist by @Zetrith into a simple program that can be called. I've hosted this program in my own repo for now, but if Zetrith wants to fork it and add it here, that's fine.

The program itself is called Publicize, and I've released a binary for it [here](https://github.com/jacobEAdamson/publicize/releases/tag/v1.0.0). An example of using it (In my case from the git bash shell) looks like this:

```bash
Publicize "/c/Program Files (x86)/Steam/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/Assembly-CSharp.dll"
```

This will result in an `Assembly-CSharp_public.dll` file appearing in the Rimworld Managed folder. Cloning the Zetrith multiplayer mod into the correct spot and building should now produce a valid binary.

```bash
cd "/c/Program Files (x86)/Steam/steamapps/common/RimWorld/Mods"
git clone "https://github.com/Zetrith/Multiplayer.git"
```

Hopefully this helps people looking to work on this wonderful mod! All thanks be to @Zetrith

**Comment by tindolt** [comment]
You know people already had access to this right?

**Comment by jacobEAdamson** [comment]
I didn't find them in the repo. Perhaps if they're there, a link could be added to the main README that points it out? I'm just saying that I found this project difficult to build just by looking at the README

**Comment by tindolt** [comment]
its the same as any other c# mod

**Comment by Proximitron** [comment]
THIS helped me figure that out. Yes, developers "should" know such things, but hey... from where exactly. There are thousands of small things most of us have never heard of, like this very cool tool that can publicize dll's.  Please add this to the readme file and thank you for this great mod.

**Comment by RedPandasRule021** [comment]
Guys, if u DONT know how to build in rimworld here's how: click on architect then structure. Then u can right click on wooden wall and change materials. Its so simple.

**Comment by sumghai** [comment]
@RedPandasRule021 - These instruction are for coders to re-compile a publicized version of the RimWorld source code. It has NOTHING to do with players "building" things in the game.
