### ISSUE TITLE
Fertile Fields Issues

### ISSUE THREAD

**Issue by Yerfle** [Zetrith/Multiplayer#73]
I found an issue with Fertile Fields which effects both multiplayer games (desyncs) and single player games. Basically if there is an object to construct with level 4 required construction skill or higher (say a dining chair) and someone with a construction skill below 4 is on the map, so long as fertile fields is enabled these low level constructors attempt to build the high level object and the game freezes/desyncs whenever this happens.

Is a bit of an issue on new game saves but becomes less of a problem as everyone levels up construction.

**Comment by tindolt** [comment]
This doesn't have anything to do with zmp, please go to fertile fields issue area and post there.

**Comment by Yerfle** [comment]
Well you listed this as a fully compatable mod so i thought it appropriate to let you know it isn't...
