### ISSUE TITLE
Compability issue with Andriods mod.

### ISSUE THREAD

**Issue by qsdoosix** [Zetrith/Multiplayer#74]
Hello Zetrith. First thank you for this great mod!  However, i have a issue about the compability with mod "Androids".
1. The droid fabricator is malfunctioned and produced some "bugged" Droids which can't set its working priority or rally for combat.  And when i try to build another droid it throws exception
```
Thing droid colonist is inaccessible
Verse.Log:Error(String, Boolean)
Multiplayer.Client.Sync:WriteSyncObject(ByteWriter, Object, SyncType)
Multiplayer.Client.Sync:WriteSync(ByteWriter, Pawn)
Multiplayer.Client.<>c:<.cctor>b__56_66(ByteWriter, Pawn_WorkSettings)
Multiplayer.Client.<>c__DisplayClass0_0`1:<Add>b__0(ByteWriter, Object)
Multiplayer.Client.Sync:WriteSyncObject(ByteWriter, Object, SyncType)
Multiplayer.Client.SyncMethod:DoSync(Object, Object[])
Multiplayer.Client.SyncTemplates:General(MethodBase, Object, Object[])
Multiplayer.Client.SyncTemplates:Prefix_2(MethodBase, Object, Object, Object)
RimWorld.Pawn_WorkSettings:SetPriority_Patch2(Object, WorkTypeDef, Int32)
RimWorld.Pawn_WorkSettings:EnableAndInitialize()
Androids.DroidUtility:MakeDroidTemplate(PawnKindDef, Faction, Int32, List`1, Int32)
Androids.Building_DroidCrafter:MakePawnAndInitCrafting(DroidCraftingDef)
Androids.<>c__DisplayClass3_0:<InitiatePawnCrafting>b__1()
Verse.FloatMenuOption:Chosen(Boolean, FloatMenu)
Verse.FloatMenuOption:DoGUI(Rect, Boolean, FloatMenu)
Verse.FloatMenu:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

```

2. Opening Droid's charactor window cause desync.
2. Android printer throws exception when opening the resource settings window. 

```
Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
Verse.Log:Error(String, Boolean)
Verse.Widgets:EnsureMousePositionStackEmpty()
Verse.Root:Update_Patch1(Object)
Verse.Root_Play:Update()
```

Hope this can help you fix the issue

**Comment by ethanhulse** [comment]
The first two issues are likely due to the Androids mod not properly assigning privacy parameters to the droid objects. The Multiplayer mod probably can't access the private or even protected data members in the droid class. 
 Do similar issues happen with other core mods?
As for the third, the Droid mod's GUI handles click and scroll events incorrectly; because the game can compensate for poor scripting, these issues would not present themselves unless there is another mod affecting the interface.
Note that I'm just throwing out my ideas

**Comment by tindolt** [comment]
Zetrith does not do compatibility patches for other peoples mods.
