### ISSUE TITLE
Steam Mod

### ISSUE THREAD

**Issue by CTH999** [Zetrith/Multiplayer#75]
So, I'm just wondering, if this is a rimworld mod, why isn't it on steam, where you buy rimworld?

Putting it in the workshop will:

Allow more people to use this mod
Make this mod easier to install (Especially for people who can't find the rimworld folder)
From what I have heard, it should make updates easier on you.
It centralizes it.
You can still do test branches on GitHub, and only the official releases on steam.

I'm just curios!

However, ultimately, this is just a suggestion! It's your choice.

**Comment by PirateGuy** [comment]
[https://github.com/Zetrith/Multiplayer/wiki/FAQ](https://github.com/Zetrith/Multiplayer/wiki/FAQ)

_**Is the mod available through Steam?**
Not yet. A Workshop release will be available after the mod gets more stable._

**Comment by CTH999** [comment]
Ok

Well, you might consider putting the less stable version there as well.

I.E. "Rimworld Multiplayer- Dev" (That is this version, and it is warned that it is unstable)

Once stable:

"Rimworld Multiplayer- Releast"- The stable version. Updated less often, but more stable!

**Comment by tindolt** [comment]
This is how zetrith wanted it, he said he will release when he is ready to, no need to badger about that just be patientand its not much harder to just click a link to github and download into mods folder.

**Comment by sbacklund2013** [comment]
I agree the Mod would be great on the workshop, however I think the best choice is waiting for a more stable version. It is not hard to install the mod as it is so players not worried about stability can still enjoy this great mod.

**Comment by CTH999** [comment]
@tindolt 

Okay, fair enough

@sbacklund2013 
Fair enough, I do admit I disagree with how he’s doing it, but I won’t “badger” him about it.

It’s just that many unstable mods are theire, just with warningws.

Well, if that is what zetrith wanted, then I will respect his whishes!
