### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by brandon7o** [Zetrith/Multiplayer#77]
I don't see my saves for multiplayer. I click save replay, but I cant go back to the game after I leave and try to load it up. I can only see save replay by the way.

**Comment by g0ddish** [comment]
A replay is a save in MP, just host that replay from the Multiplayer menu?

**Comment by brandon7o** [comment]
I tried but I can't see anything on the host tab in the menu. It's just blank.On Mar 28, 2019 11:09 AM, Alex Hughes <notifications@github.com> wrote:A replay is a save in MP, just host that replay from the Multiplayer menu?

**Comment by tindolt** [comment]
Can you post screenshots please

**Comment by brandon7o** [comment]
![20190401154838_1](https://user-images.githubusercontent.com/49005037/55355344-02c80000-5496-11e9-95fe-74d024a09813.jpg)
![20190401154811_1](https://user-images.githubusercontent.com/49005037/55355347-03f92d00-5496-11e9-893a-c1c6e9b5d4fd.jpg)

**Comment by brandon7o** [comment]
I waited for about 5 minutes to see if anything would load up. Not sure what is exactly wrong.

**Comment by tindolt** [comment]
ok well are you trying to load a singleplayer save? if so go to singleplayer load up your save then hit esc, and host server or host multiplayer dont remember what it says then when that is loaded up and done hosting then save replay and you should find it in your host tab on the main menu.
