### ISSUE TITLE
Host client tick falling behind

### ISSUE THREAD

**Issue by Qinusty** [Zetrith/Multiplayer#79]
While hosting the multiplayer game, I am unable to run the game at 3x speed and in some cases 2x speed. This also happens when my friend hosts the same replay on his PC (I see the lag, not him).

After 2-3 seconds of running at these speeds I fall behind significantly in ticks.

Some details:
- Two player multiplayer
- Two settlements
- Other player sees no issues despite being remote from the server (me)
- CPU/GPU/RAM etc remain low and are not under any form of heavy load

I'm not too sure how things are kept in sync but any guidance would be appreciated.

**Comment by tindolt** [comment]
Sometimes it's the host or clients connection not being strong or also sometimes it's the game having too many things to update. Check both internet connections if that doesn't work reset and try one world with small amount of pawns

**Comment by Qinusty** [comment]
Upon further investigation, I have further detailed this issue further here https://github.com/Parexy/Multiplayer/issues/32
