### ISSUE TITLE
Pause on urgend letter

### ISSUE THREAD

**Issue by FSanta** [Zetrith/Multiplayer#81]
We are having a blast with this mod, thanks for all the effort!

Bigger raids cause some seconds of freeze, which is not a big problem per se, but the time goes on and we get hit pretty hard before we have a chance to react.
The option "Pause on urgend letter" would resolve this problem, but can't be enabled.
Is this intended?

**Comment by RedPandasRule021** [comment]
Dude, go into settings and turn off "pause on urgent letter"

**Comment by jusito** [comment]
Would be interesting for me too.
Even if "Pause on urgent letter" is enabled in a non-multiplayer savegame, after "host a server" I can't enable this.

@RedPandasRule021 
Iam pretty sure he want to enable it, so its already disabled. Even in multiplayer mod v 0.4.4 there is no Mod option visible for me to enable it.

**Comment by RedPandasRule021** [comment]
Umm... I was kinda hacked a while ago so um yeah don't even have the game
as well. Also spelt urgent wrong.
