### ISSUE TITLE
Desync when people enter the map

### ISSUE THREAD

**Issue by lc-thomas** [Zetrith/Multiplayer#84]
Whenever someone enter the colony map (visitors, traders, raiders, siege), the game would desync.

Other players can join back when those people are gone / dead.

**Comment by mrhgravity** [comment]
Same was happening to me and my friend. Disabling Hospitality and Allow Tool mods made it stop.

**Comment by K-marad** [comment]
We removed all mods except Core and Multiplayer, and still when first caravan arrives there is a desync.
