### ISSUE TITLE
Independant Pausing

### ISSUE THREAD

**Issue by mrhgravity** [Zetrith/Multiplayer#85]
I noticed in the reveal video https://youtu.be/ZOaf524Z7P4?t=205

It looks like there is independent pausing and fast forwarding among the colonies. My friend and I are linked in our time manipulation however even though we're on two seperate maps. We're missing the buttons underlined below. So if one of us pauses or fast forwards it affects both of us. Is there a way to change that or is that part of the current release?

![image](https://user-images.githubusercontent.com/49600351/56086686-2df50c80-5e11-11e9-95c9-f1b1c6a00135.png)

**Comment by EKafer** [comment]
The time is the same for both of you. Its necessary for the caravans and everything work as expected.
