### ISSUE TITLE
Error with Rimatomics Compatability

### ISSUE THREAD

**Issue by cmurph103** [Zetrith/Multiplayer#90]
I was hosting a game with the following mods enabled In this order: (creator)
Hugslib (unlimitedhugs) , miscellaneous ‘CORE’ (Haplo_X1),  modmanager (Fluffy),  jecstools (jecrell),  morevanilla turrets extension pack (XeoNovaDan), Expanded prothsthetics and organ engeneering (Ykara), more trade ships (pinochemicali), [XND] Turret Extension (XeoNovaDan), embrasure (brunayla), morevanillafactions (avis), glittertech (Sam_), increase stack (taveron), rimatomics (dubwise), [kv] trading spot - 1.0 (kiame vivacity), edb prepare carefully (edbmods),  morevanillaturrets 1.0 (paradox), farmable neutroamine (nanonator).
Two (2) friends and I were playing when I finished Rimatomics nuclear power and went to interact with the command console for the reactor. When I interacted with the command console and the panel for its control popped up everyone, including myself, desynched with the error stating "incorrect random map state 0".

**Comment by wandisimo** [comment]
Move Rimatomics up in your load order, Im pretty sure it needs to be before glitterworld.
