### ISSUE TITLE
Crossplatform is broken for any mod

### ISSUE THREAD

**Issue by rkost** [Zetrith/Multiplayer#92]
## Scenario

Linux (`arch, 5.0.12`) as a host with a Windows 10 computer as a client. 

When having no mods enabled (except *core* and *multiplayer* obviously) the windows client is able to join the world that is hosted on my linux machine. It seems that there are no issues at all.

However, when enabling *any* mod (e.g. *RT-Fuse* or *Expanded Prosthetics and Organ Engineering*) the windows client shows an error message: `RecipeDef: Hash_Diff`. The game runs from steam, all mods were downloaded from the steam workshop on both systems.

## MISC

I never worked with C#, however I guess that this check fails

https://github.com/Zetrith/Multiplayer/blob/f86be78fc35c81848b6fb17ddf9792c474946f31/Source/Common/ServerConnection.cs#L54-L58

I skimmed through the repo and found that for every mod there are some crc32 checksums being calculated for every mod. Is there a way, that they are different for linux clients?

I also tried to skip the check mentioned above but I am somehow unable to build the code on my linux machine. Maybe it would be cool to have a mod option that allows to skip the hash checks to check if multiplayer works at all even when the hashes do not match? Whatever: Do you have any clue why there is a Hash_Diff at all?

**Comment by rkost** [comment]
Apparently [this fork](https://github.com/vasilevp/Multiplayer) has some commits that fix the issue. Would be nice, if [this wiki page](https://github.com/Zetrith/Multiplayer/wiki/Mod-support) would mention that.

**Comment by Jostino** [comment]
Well today i noticed the same problem, hoster was on Win10 and me (client trying to connect through steam) on Linux (Mint).
